version: "3"
services:
  snapserver:
    image: jaedb/snapserver
    ports:
      - 1704:1704
      - 1705:1705
      - 1780:1780
    volumes:
      - HOST_SNAPCAST_TEMP:/tmp
      - ./docker/snapserver.conf:/etc/default/snapserver.conf
  mopidy:
    image: jaedb/iris
    build:
      context: .
    depends_on:
      - snapserver
    ports:
      - 6600:6600
      - 6680:6680
    volumes:
      # Uncomment these lines to use a host-managed development build
      #- ./mopidy_iris:/iris/mopidy_iris
      #- ./IRIS_VERSION:/iris/IRIS_VERSION
      - ./docker/mopidy.conf:/config/mopidy.conf
      - HOST_MUSIC_DIRECTORY:/var/lib/mopidy/media
      - HOST_SNAPCAST_TEMP:/tmp
