name: Sync Fork

on:
  schedule:
    - cron: '0 10 * * *'
  workflow_dispatch: # on button click

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.2
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          owner: jaedb
          base: master
          head: master
